# Generated by Django 6.0.5 on 2026-06-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_driverprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/licenses/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/profiles/'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
